let
    Source = #table(type table [#"WorkspaceId" = text, #"ReportId" = text, #"ReportName" = text, #"ReportType" = text, #"SemanticModelId" = text, #"ReportURL" = nullable text, #"RunTimestampUTC" = datetime], {
        {"548cf0e0-454d-5ad9-9dd6-733f48e562a4", "75035fd9-9034-5b26-8bd5-095261ef26fa", "Revenue Overview", "PowerBIReport", "dbe3fb0b-e5ae-5ca3-aa98-42df1a87030b", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"548cf0e0-454d-5ad9-9dd6-733f48e562a4", "582a8ce0-5eaf-52de-a59e-534183a0c0ed", "Regional Performance", "PowerBIReport", "dbe3fb0b-e5ae-5ca3-aa98-42df1a87030b", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"548cf0e0-454d-5ad9-9dd6-733f48e562a4", "6ea93bbf-3cda-5679-87ab-f9bab68424c8", "Customer Trends", "PowerBIReport", "b2e0a1e7-cc92-5761-bfd4-aca212b0320b", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"548cf0e0-454d-5ad9-9dd6-733f48e562a4", "0455a2f3-f7d7-5d87-8fab-5e2dc3d38abd", "Commercial Outlook", "PowerBIReport", "5b91b2f7-42b8-5b77-996c-645f26ca742d", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"548cf0e0-454d-5ad9-9dd6-733f48e562a4", "06b15101-4d48-52e8-a13e-315b782dba5a", "Market Summary", "PowerBIReport", "5b91b2f7-42b8-5b77-996c-645f26ca742d", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"72af45ab-47a8-5b5c-a73e-f376e5cfa4c9", "2a0ee215-a10f-50b9-8108-3b5ac05382a5", "Production Overview", "PowerBIReport", "9aacdf66-e2c2-5ea0-bca8-053ef19398f0", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"72af45ab-47a8-5b5c-a73e-f376e5cfa4c9", "6553a38e-f98c-5d4f-ad9b-1b9ce9aa2f92", "Throughput Detail", "PowerBIReport", "9aacdf66-e2c2-5ea0-bca8-053ef19398f0", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"72af45ab-47a8-5b5c-a73e-f376e5cfa4c9", "bbbfa019-512f-5dbf-b4e7-10a8872426a1", "Operations Scorecard", "PowerBIReport", "ee3332e7-458a-5953-b9e3-028a9f71c488", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"72af45ab-47a8-5b5c-a73e-f376e5cfa4c9", "29ada406-a073-59ad-b12a-852027c79121", "Daily Operations", "PowerBIReport", "d8af86a8-670b-5324-ba88-dc35cf761deb", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"72af45ab-47a8-5b5c-a73e-f376e5cfa4c9", "74c2d003-1dea-570f-8e93-6d87dbcfcb4b", "Capacity Overview", "PowerBIReport", "d8af86a8-670b-5324-ba88-dc35cf761deb", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"ec69cb8d-2f63-5925-836e-310f33014929", "259d9102-4c5b-52cd-b934-c75e18e56e54", "Quality Overview", "PowerBIReport", "b632e64b-5c32-5ab5-980b-500f5d0cf70f", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"ec69cb8d-2f63-5925-836e-310f33014929", "f4db7052-228f-56b7-8bb2-5ee3075705a0", "Quality Events", "PowerBIReport", "b632e64b-5c32-5ab5-980b-500f5d0cf70f", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"ec69cb8d-2f63-5925-836e-310f33014929", "591c1c46-cf53-54a7-9d84-0f8102be27f0", "Investigation Tracker", "PowerBIReport", "a0cd07bb-6249-537d-bdee-fb3770174da9", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"ec69cb8d-2f63-5925-836e-310f33014929", "dd0b0278-0923-5e74-9f76-223fed49fd8d", "Release Readiness", "PowerBIReport", "e6d54184-125e-5884-a8b0-8b20f93e285c", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"ec69cb8d-2f63-5925-836e-310f33014929", "1a264cd7-373a-5299-8738-6e3b819e8706", "Quality Scorecard", "PowerBIReport", "e6d54184-125e-5884-a8b0-8b20f93e285c", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"7fd6d6af-391f-56e1-baf2-1791194b493a", "1422b543-2509-5dc5-9052-c0e94730d82e", "Demand Outlook", "PowerBIReport", "d57e694e-8500-541f-b74d-a1ecc232cb08", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"7fd6d6af-391f-56e1-baf2-1791194b493a", "612047bb-964c-58c2-918a-c929049d18ac", "Supply Position", "PowerBIReport", "d57e694e-8500-541f-b74d-a1ecc232cb08", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"7fd6d6af-391f-56e1-baf2-1791194b493a", "051acdaa-cc2c-5361-b256-49890f7c1d20", "Inventory Overview", "PowerBIReport", "1b299595-66f2-5935-8708-c11cb07e3196", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"7fd6d6af-391f-56e1-baf2-1791194b493a", "07dd42d0-061c-59fa-8a2f-381f52d58008", "Planning Dashboard", "PowerBIReport", "29f38210-7917-52dd-a9e7-f07c5b03b222", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"7fd6d6af-391f-56e1-baf2-1791194b493a", "e5eaa911-ab5b-537c-a7dd-a8c671902d74", "Schedule Attainment", "PowerBIReport", "29f38210-7917-52dd-a9e7-f07c5b03b222", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"0da27c99-e0b3-5be5-94b9-4b871dbe7f50", "dba0ab56-f5eb-50ba-b977-08a2b6847c7e", "Product Performance", "PowerBIReport", "5b1d441b-8620-50a4-9636-ca31cd3fb2b9", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"0da27c99-e0b3-5be5-94b9-4b871dbe7f50", "d7d62101-5e7d-5a4d-ba4a-9c1bc6ace22b", "Portfolio Overview", "PowerBIReport", "5b1d441b-8620-50a4-9636-ca31cd3fb2b9", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"0da27c99-e0b3-5be5-94b9-4b871dbe7f50", "207d5f5a-7028-57e5-a7a8-7c1d4357dc92", "Feature Adoption", "PowerBIReport", "3bd0eb12-6ad2-53dd-9e24-11b73e89d959", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"0da27c99-e0b3-5be5-94b9-4b871dbe7f50", "d3664f00-f9de-5eec-b00d-6d05b3c3dae7", "Product Scorecard", "PowerBIReport", "f6db0003-1517-5fb0-8962-409c25108cbe", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"0da27c99-e0b3-5be5-94b9-4b871dbe7f50", "64cc41a9-c37f-5649-b57f-b7e7f769c08f", "Lifecycle Review", "PowerBIReport", "f6db0003-1517-5fb0-8962-409c25108cbe", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"f15f8786-f6ce-550a-a351-870b50a85adb", "824750e1-8fd4-524c-bd87-092212e972ba", "Finance Overview", "PowerBIReport", "e2b38bce-7e57-5ebb-8e20-89c256cc6c00", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"f15f8786-f6ce-550a-a351-870b50a85adb", "4d796a85-90ff-5bf1-ab06-6007d9442410", "Budget vs Actual", "PowerBIReport", "e2b38bce-7e57-5ebb-8e20-89c256cc6c00", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"f15f8786-f6ce-550a-a351-870b50a85adb", "78ae265c-58c0-5266-a666-5e2e154c5940", "Cost Review", "PowerBIReport", "059fe7a4-df31-541c-871f-822c9b4b7983", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"f15f8786-f6ce-550a-a351-870b50a85adb", "32b45cc0-48c6-55c1-abc4-d61aa4a8bb25", "Expense Detail", "PowerBIReport", "65582633-28c4-5cd5-ad4a-8b9843ee5de9", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"f15f8786-f6ce-550a-a351-870b50a85adb", "46a508ea-614b-55b1-a48a-2277fda811a6", "Financial Outlook", "PowerBIReport", "65582633-28c4-5cd5-ad4a-8b9843ee5de9", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"573efda1-a917-547a-8e8d-0e372635bebf", "d1970397-cae5-5faf-8935-4a8fb7c58d44", "Research Portfolio", "PowerBIReport", "4b29d0b0-e136-559c-ba31-529ab9050979", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"573efda1-a917-547a-8e8d-0e372635bebf", "708286e9-7309-5e19-8e26-6b49f29d7504", "Project Progress", "PowerBIReport", "4b29d0b0-e136-559c-ba31-529ab9050979", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"573efda1-a917-547a-8e8d-0e372635bebf", "62b12c21-85cb-5e2a-b52f-3650dcce45d9", "Study Overview", "PowerBIReport", "8119de37-0c3e-5bb0-95fa-8abce5bd2c84", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"573efda1-a917-547a-8e8d-0e372635bebf", "ae690ca4-ae72-5d82-8be0-1ba41ecc7bee", "Resource Outlook", "PowerBIReport", "c0890614-b5fa-5644-bd8b-fb6de4fb43f9", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"573efda1-a917-547a-8e8d-0e372635bebf", "67ad18d3-7b61-5ad5-b2af-33310cb1fe02", "Research Scorecard", "PowerBIReport", "c0890614-b5fa-5644-bd8b-fb6de4fb43f9", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"9324b505-a143-5aaa-8049-27dd51e55af7", "75360703-344d-5738-af24-25908fa85da9", "Service Overview", "PowerBIReport", "3afaac19-f77b-5908-b6ae-33e13a16aff1", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"9324b505-a143-5aaa-8049-27dd51e55af7", "e55ab5e3-028b-5071-b648-65f7b3476140", "Support Performance", "PowerBIReport", "3afaac19-f77b-5908-b6ae-33e13a16aff1", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"9324b505-a143-5aaa-8049-27dd51e55af7", "6ead570d-0e75-5bd5-b428-37d2a87510b6", "Request Tracker", "PowerBIReport", "19e53278-1045-58e3-830f-ecc6befcb452", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"9324b505-a143-5aaa-8049-27dd51e55af7", "2b592983-06cd-5074-bec5-4e2e57ae79c9", "Platform Overview", "PowerBIReport", "21bd7058-3701-558e-89c8-7c2c60657d65", null, #datetime(2026, 9, 12, 12, 0, 0)},
        {"9324b505-a143-5aaa-8049-27dd51e55af7", "504252f9-21ee-5452-aec5-652b3df02a72", "Service Scorecard", "PowerBIReport", "21bd7058-3701-558e-89c8-7c2c60657d65", null, #datetime(2026, 9, 12, 12, 0, 0)}
    }),
    WithKey = Table.AddColumn(Source, "ModelKey", each [WorkspaceId] & "|" & [SemanticModelId], type text),
    Joined = Table.NestedJoin(WithKey, {"ModelKey"}, #"Semantic Models", {"ModelKey"}, "Model", JoinKind.LeftOuter),
    Expanded = Table.ExpandTableColumn(Joined, "Model", {"SemanticModelName", "SemanticModelOwner", "IsRefreshable", "LastRefreshUTC", "LastRefreshEndUTC", "LastRefreshStatus", "LastRefreshDurationSeconds", "HealthStatus"}),
    WorkspacesJoined = Table.NestedJoin(Expanded, {"WorkspaceId"}, Workspaces, {"WorkspaceId"}, "Workspace", JoinKind.LeftOuter),
    Result = Table.ExpandTableColumn(WorkspacesJoined, "Workspace", {"WorkspaceName"})
in
    Result